In [1]:
import numpy as np
# Random Generators 
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg
# Application of Random Generators
# Generate 5 different arrays
array_RG = gen(pcg(seed = 365))
array_column_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_column_3 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
array_column_4 = array_RG.exponential(scale = 4, size = (1000))
array_column_5 = array_RG.geometric(p = 0.7, size = (1000))

In [2]:
# Generate 5 different arrays
random_test_data = np.array([array_column_1,
                             array_column_2,
                             array_column_3, 
                             array_column_4,
                             array_column_5])
print(random_test_data)

[[ 1.59077303  2.28243293  1.81098674 ...  0.1973629  -2.21015722
   2.91161235]
 [ 6.42174295  8.57902322  5.17270135 ...  4.3465854   8.2176402
   7.90337695]
 [10.14698427 15.93309953 -0.46878789 ...  2.66485989 12.69328115
  11.79840961]
 [ 6.91500737  6.243605    2.44997251 ...  0.80935387  0.50644607
   4.86816939]
 [ 1.          1.          1.         ...  1.          2.
   1.        ]]


In [3]:
print(random_test_data.shape)

(5, 1000)


In [4]:
# Transpose
# Generate 5 different arrays
random_test_data = np.array([array_column_1,
                             array_column_2,
                             array_column_3, 
                             array_column_4,
                             array_column_5]).transpose()
print(random_test_data)

[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]


In [5]:
print(random_test_data.shape)

(1000, 5)


In [6]:
# save the data in csv file
# How to save the random data in csv
np.savetxt("Random-Test-from-Numpy.csv",
           random_test_data,
           fmt = "%s", delimiter = ',')


In [15]:
# np.loadtxt() it can not load categorical data
# loadtxt is faster 
# but it breaks when we feed it incomplete or
# ill - formatted datasets
lending_co_data_numeric_1 = np.loadtxt('Random-Test-from-Numpy.csv', delimiter= ',')
print(lending_co_data_numeric_1)

[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]


In [16]:
# np.loadtxt() vs np.genfromtxt()
# genformtxt have more flexibility
# slightly slower but can handle missing values
lending_co_data_numeric_2 = np.genfromtxt('Random-Test-from-Numpy.csv', delimiter= ',')
print(lending_co_data_numeric_2)

[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]


In [17]:
np.array_equal(lending_co_data_numeric_1, lending_co_data_numeric_2)

True

In [20]:
#np.genfromtxt() it will read categorical data 
# genformtxt have more flexibility
# slightly slower but can handle missing values
lending_co_data_numeric_2 = np.genfromtxt('lending-co-LT.csv', delimiter= ',')
print(lending_co_data_numeric_2)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00       nan       nan ...       nan       nan 1.660e+04]
 [2.000e+00       nan       nan ...       nan       nan 1.660e+04]
 ...
 [1.041e+03       nan       nan ...       nan       nan 1.660e+04]
 [1.042e+03       nan       nan ...       nan       nan 1.560e+04]
 [1.043e+03       nan       nan ...       nan       nan 1.660e+04]]


In [26]:
#np.genfromtxt() it will read categorical data 
# genformtxt have more flexibility
# slightly slower but can handle missing values
lending_co_data_numeric_2 = np.genfromtxt('lending-co-LT.csv',
                                          delimiter= ',',
                                          dtype= np.int64)
print(lending_co_data_numeric_2)

[[  -1   -1   -1 ...   -1   -1   -1]
 [   1   -1   -1 ...   -1   -1   -1]
 [   2   -1   -1 ...   -1   -1   -1]
 ...
 [1041   -1   -1 ...   -1   -1   -1]
 [1042   -1   -1 ...   -1   -1   -1]
 [1043   -1   -1 ...   -1   -1   -1]]


In [27]:
lending_co_data_numeric_1[0,0]+lending_co_data_numeric_2[0,1]

0.5907730323967642