In [1]:
import numpy as np

In [2]:
a = np.array([3,8,2,67,45])

In [3]:
a

array([ 3,  8,  2, 67, 45])

In [4]:
print(a.size)
print(a.shape)
print(a.dtype)
print(len(a))

5
(5,)
int32
5


In [5]:
# create two D data
b = np.array([[10,11,13,14],[45,22,9,2],[6,5,1,8]])

In [6]:
print("Array is :")
print(b)
print("shape is :", b.shape)
print("size is :",b.size)
print("data type is :",a.dtype)
print("length is :",len(b))
print("Type is :",type(b))

Array is :
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
shape is : (3, 4)
size is : 12
data type is : int32
length is : 3
Type is : <class 'numpy.ndarray'>


In [7]:
# Array Operation
# 1. Item Accessing: Indexing: Subscripting: Slicing
# 2. Item Insertion
# 3. Item Deletion
# 4. Arithmatic

In [8]:
c = np.array([[[10,100], [11,13],[13,130],[14,140], 
               [45,145],[22,122],[9,19],[2,12],
               [6,16],[5,15],[1,11],[8,18]]])
print(c)

[[[ 10 100]
  [ 11  13]
  [ 13 130]
  [ 14 140]
  [ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]
  [  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]


In [9]:
print(c.ndim)

3


In [10]:
# Do subsripting
c[0,0]

array([ 10, 100])

In [11]:
c[:, -2]

array([[ 1, 11]])

In [12]:
c.shape

(1, 12, 2)

In [13]:
c[:, -2: -1]

array([[[ 1, 11]]])

In [14]:
c[0,1]

array([11, 13])

In [15]:
b[:,-2:-1]

array([[13],
       [ 9],
       [ 1]])

In [16]:
b

array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [17]:
b[2,:]

array([6, 5, 1, 8])

In [18]:
b[2,:].ndim

1

In [19]:
b[2,:].shape

(4,)

In [20]:
print(b[-1:,:])
print(c[:1, :2, :1])
print(c[:, 1:2, :1])
print(c[-2:, -1:, :1])
print(c[:2, -2:, :])

[[6 5 1 8]]
[[[10]
  [11]]]
[[[11]]]
[[[8]]]
[[[ 1 11]
  [ 8 18]]]


In [21]:
# Item assignment
b[1,2] = 90
b 

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [22]:
# Item Insertion
a

array([ 3,  8,  2, 67, 45])

In [23]:
a =np.append(a, 80)
a

array([ 3,  8,  2, 67, 45, 80])

In [24]:
np.append(b, [[9,90,900,9000]], axis = 0)

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [25]:
np.append(b, [[9],[90],[900]], axis = 1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])

In [26]:
# Deletion
np.delete(b, 0, axis = 0)

array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [27]:
# Arithmatic Operation
b -30

array([[-20, -19, -17, -16],
       [ 15,  -8,  60, -28],
       [-24, -25, -29, -22]])

In [28]:
b+40

array([[ 50,  51,  53,  54],
       [ 85,  62, 130,  42],
       [ 46,  45,  41,  48]])

In [29]:
b.reshape(2,6,1,1)

array([[[[10]],

        [[11]],

        [[13]],

        [[14]],

        [[45]],

        [[22]]],


       [[[90]],

        [[ 2]],

        [[ 6]],

        [[ 5]],

        [[ 1]],

        [[ 8]]]])

In [31]:
b.dtype

dtype('int32')

In [34]:
import cv2